version: '2.3'
services:
  openemis-mailhog:
    image: phpdockerio/mailhog:latest
    container_name: openemis-mailhog-2
    ports:
      - "8125:8025"
  openemis-mysql-3:
    image: moelk/openemis-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: openemis
      MYSQL_USER: openuser
      MYSQL_PASSWORD: openpass
    command: --max_allowed_packet=32505856
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "8106:3306"
    restart: always
  openemis-nginx:
    image: phpdockerio/nginx:latest
    container_name: openemis-nginx-2
    volumes:
        - ./nginx:/var/www/myapp
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8180:80"
    links:
      - openemis-php-fpm
    restart: always
  openemis-php-fpm:
    image: moelk/openemis-php-fpm:latest
    container_name: openemis-php-fpm-2
    volumes:
      - ./php-fpm:/var/www/myapp
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    links:
      - openemis-mailhog
      - openemis-mysql-3
