version: '2.3'
services:
  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   environment:
  #     STAGE: local
  #     DOMAINS: 'sis.moe.gov.com -> http://openemis-nginx:80' # saml.moe.gov.com -> http://saml-moe:443, apim.moe.gov.com -> http://api-manager:9443
  openemis-mailhog:
    image: phpdockerio/mailhog:latest
    container_name: openemis-mailhog-2
    ports:
      - "8125:8025"
  openemis-mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: openemis
      MYSQL_USER: openuser
      MYSQL_PASSWORD: openpass
    command:  '--sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856'
    ports:
      - "8106:3306"
    restart: always
  openemis-nginx:
    build: ./nginx
    container_name: openemis-nginx-2
    ports:
    - "8180:80"
    links:
      - openemis-php-fpm
    restart: always
  openemis-php-fpm:
    build: ./php-fpm
    volumes:
       - ./php-fpm/app:/var/www/myapp
       - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    container_name: openemis-php-fpm-2
    links:
      - openemis-mailhog
      - openemis-mysql
